#ifndef __MAIN_H__
#define __MAIN_H__

enum MAIN_FWLINKS { MAIN_FWLINKS_LOCAL, MAIN_FWLINKS_360, MAIN_FWLINKS_365, MAIN_FWLINKS_368 };
enum MAIN_TAIS { MAIN_TAIS_LOCAL, MAIN_TAIS_DISABLED, MAIN_TAIS_VANILLA, MAIN_TAIS_DEFAULT, MAIN_TAIS_DEFAULT_YAMT };
enum MAIN_SUBMAINS { MAIN_SUBMAINS_VSHELL, MAIN_SUBMAINS_IMCUNLOCK, MAIN_SUBMAINS_MODORU, MAIN_SUBMAINS_FWTOOL, MAIN_SUBMAINS_APPI, MAIN_SUBMAINS_RNEAR };
#endif