#ifndef __CFGK_H__
#define __CFGK_H__

enum CFGK_BRIDGE {
    CFGK_BRIDGE_SET_PATCHED = 0,
    CFGK_BRIDGE_EXT2GRW,
    CFGK_BRIDGE_GET_LOC,
    CFGK_BRIDGE_GET_MINFW,
    CFGK_BRIDGE_GET_SET_LAUNCHARG,
    CFGK_BRIDGE_GET_SET_SUBMAIN,
    CFGK_BRIDGE_GET_SET_FW_DL_LINK,
    CFGK_BRIDGE_GET_SET_TAI_DL_LINK,
    CFGK_BRIDGE_SET_APP_INSTALLER_CFG,
    CFGK_BRIDGE_GET_APP_INSTALLER_CFG,
    CFGK_BRIDGE_GET_SET_REMOTE,
    CFGK_BRIDGE_GET_SET_ENSO_FLAG,
    CFGK_BRIDGE_ABBY_RESET
};

#endif